[2024-02-25 14:59:45,574: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-25 14:59:45,933: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-25 14:59:45,943: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-25 14:59:49,277: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-25 14:59:49,281: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 14:59:49,287: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 14:59:49,287: INFO: common: created directory at: artifacts]
[2024-02-25 14:59:49,287: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-25 14:59:49,287: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 14:59:53,841: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 14:59:54,104: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-25 14:59:54,111: INFO: main: *******************]
[2024-02-25 14:59:54,111: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-25 14:59:54,111: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 14:59:54,111: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 14:59:54,122: INFO: common: created directory at: artifacts]
[2024-02-25 14:59:54,122: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-25 14:59:54,551: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2024-02-25 14:59:54,685: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2024-02-25 14:59:55,337: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-25 14:59:55,687: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-25 14:59:55,687: INFO: main: *******************]
[2024-02-25 14:59:55,687: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-25 14:59:55,694: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 14:59:55,694: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 14:59:55,694: INFO: common: created directory at: artifacts]
[2024-02-25 14:59:55,694: INFO: common: created directory at: artifacts\training]
[2024-02-25 14:59:57,368: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2024-02-25 15:00:05,041: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-25 15:00:05,041: INFO: main: *******************]
[2024-02-25 15:00:05,041: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-25 15:00:05,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 15:00:05,041: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 15:00:05,041: INFO: common: created directory at: artifacts]
[2024-02-25 15:00:07,664: INFO: common: json file saved at: scores.json]
[2024-02-25 15:00:07,674: INFO: common: json file saved at: scores.json]
[2024-02-25 15:00:07,674: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-25 19:39:50,743: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-25 19:39:50,963: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-25 19:39:50,963: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-25 19:39:53,242: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-25 19:39:53,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 19:39:53,264: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 19:39:53,264: INFO: common: created directory at: artifacts]
[2024-02-25 19:39:53,264: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-25 19:39:53,264: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 19:39:56,506: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 19:39:56,645: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-25 19:39:56,645: INFO: main: *******************]
[2024-02-25 19:39:56,651: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-25 19:39:56,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 19:39:56,651: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 19:39:56,651: INFO: common: created directory at: artifacts]
[2024-02-25 19:39:56,651: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-25 19:39:56,866: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2024-02-25 19:39:57,018: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2024-02-25 19:39:57,541: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-25 19:39:57,777: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-25 19:39:57,777: INFO: main: *******************]
[2024-02-25 19:39:57,777: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-25 19:39:57,777: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 19:39:57,777: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 19:39:57,777: INFO: common: created directory at: artifacts]
[2024-02-25 19:39:57,786: INFO: common: created directory at: artifacts\training]
[2024-02-25 19:39:58,879: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2024-02-25 19:40:13,375: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-25 19:40:13,375: INFO: main: *******************]
[2024-02-25 19:40:13,375: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-25 19:40:13,381: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 19:40:13,381: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 19:40:13,381: INFO: common: created directory at: artifacts]
[2024-02-25 19:40:18,447: INFO: common: json file saved at: scores.json]
[2024-02-25 19:40:18,449: INFO: common: json file saved at: scores.json]
[2024-02-25 19:40:18,449: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-25 19:44:56,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 19:44:56,529: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 19:44:56,531: INFO: common: created directory at: artifacts]
[2024-02-25 19:44:57,829: WARNING: module_wrapper: From c:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2024-02-25 19:45:03,907: INFO: common: json file saved at: scores.json]
[2024-02-25 19:45:10,202: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmpmf3g8kx0\model\data\model\assets]
[2024-02-25 19:51:39,557: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 19:51:39,557: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 19:51:39,557: INFO: common: created directory at: artifacts]
[2024-02-25 19:51:46,255: INFO: common: json file saved at: scores.json]
[2024-02-25 19:51:50,794: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmpitr_sfbx\model\data\model\assets]
[2024-02-25 20:00:07,963: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-25 20:00:08,184: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-25 20:00:08,184: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-25 20:00:10,277: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-25 20:00:10,293: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:00:10,293: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:00:10,293: INFO: common: created directory at: artifacts]
[2024-02-25 20:00:10,293: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-25 20:00:10,293: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 20:00:13,745: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 20:00:13,926: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-25 20:00:13,926: INFO: main: *******************]
[2024-02-25 20:00:13,926: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-25 20:00:13,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:00:13,926: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:00:13,926: INFO: common: created directory at: artifacts]
[2024-02-25 20:00:13,926: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-25 20:00:14,226: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2024-02-25 20:00:14,309: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2024-02-25 20:00:14,738: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-25 20:00:15,007: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-25 20:00:15,007: INFO: main: *******************]
[2024-02-25 20:00:15,007: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-25 20:00:15,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:00:15,007: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:00:15,007: INFO: common: created directory at: artifacts]
[2024-02-25 20:00:15,015: INFO: common: created directory at: artifacts\training]
[2024-02-25 20:00:16,064: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2024-02-25 20:00:29,511: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-25 20:00:29,511: INFO: main: *******************]
[2024-02-25 20:00:29,511: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-25 20:00:29,511: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:00:29,511: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:00:29,511: INFO: common: created directory at: artifacts]
[2024-02-25 20:00:34,243: INFO: common: json file saved at: scores.json]
[2024-02-25 20:00:34,243: INFO: common: json file saved at: scores.json]
[2024-02-25 20:00:34,248: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-25 20:03:44,604: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-25 20:03:44,791: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-25 20:03:44,791: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-25 20:03:46,774: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-25 20:03:46,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:03:46,774: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:03:46,774: INFO: common: created directory at: artifacts]
[2024-02-25 20:03:46,774: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-25 20:03:46,774: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 20:03:50,348: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 20:03:50,471: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-25 20:03:50,471: INFO: main: *******************]
[2024-02-25 20:03:50,471: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-25 20:03:50,471: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:03:50,487: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:03:50,487: INFO: common: created directory at: artifacts]
[2024-02-25 20:03:50,487: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-25 20:03:50,673: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2024-02-25 20:03:50,764: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2024-02-25 20:03:51,183: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-25 20:03:51,419: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-25 20:03:51,435: INFO: main: *******************]
[2024-02-25 20:03:51,435: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-25 20:03:51,435: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:03:51,435: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:03:51,435: INFO: common: created directory at: artifacts]
[2024-02-25 20:03:51,441: INFO: common: created directory at: artifacts\training]
[2024-02-25 20:03:52,416: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2024-02-25 20:04:05,747: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-25 20:04:05,747: INFO: main: *******************]
[2024-02-25 20:04:05,747: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-25 20:04:05,747: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 20:04:05,762: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 20:04:05,762: INFO: common: created directory at: artifacts]
[2024-02-25 20:04:10,361: INFO: common: json file saved at: scores.json]
[2024-02-25 20:04:10,361: INFO: common: json file saved at: scores.json]
[2024-02-25 20:04:13,904: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmp6wuw1bro\model\data\model\assets]
[2024-02-25 20:04:27,342: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-25 22:19:04,727: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-25 22:19:04,927: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-25 22:19:04,927: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-25 22:19:06,776: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-25 22:19:06,776: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:19:06,776: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:19:06,776: INFO: common: created directory at: artifacts]
[2024-02-25 22:19:06,776: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-25 22:19:06,776: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 22:19:10,553: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 22:19:10,642: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-25 22:19:10,642: INFO: main: *******************]
[2024-02-25 22:19:10,642: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-25 22:19:10,657: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:19:10,657: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:19:10,657: INFO: common: created directory at: artifacts]
[2024-02-25 22:19:10,657: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-25 22:19:10,821: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2024-02-25 22:19:10,907: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2024-02-25 22:19:11,229: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-25 22:19:11,430: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-25 22:19:11,446: INFO: main: *******************]
[2024-02-25 22:19:11,446: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-25 22:19:11,446: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:19:11,446: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:19:11,446: INFO: common: created directory at: artifacts]
[2024-02-25 22:19:11,451: INFO: common: created directory at: artifacts\training]
[2024-02-25 22:19:12,274: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2024-02-25 22:19:17,819: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-25 22:19:17,819: INFO: main: *******************]
[2024-02-25 22:19:17,819: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-25 22:19:17,819: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:19:17,835: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:19:17,835: INFO: common: created directory at: artifacts]
[2024-02-25 22:19:20,021: INFO: common: json file saved at: scores.json]
[2024-02-25 22:19:20,021: INFO: common: json file saved at: scores.json]
[2024-02-25 22:19:23,194: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmpb_tel9wt\model\data\model\assets]
[2024-02-25 22:19:35,245: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-25 22:24:38,568: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.
]
[2024-02-25 22:24:38,760: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-25 22:24:38,760: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-25 22:24:40,756: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-02-25 22:24:40,756: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:24:40,772: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:24:40,772: INFO: common: created directory at: artifacts]
[2024-02-25 22:24:40,772: INFO: common: created directory at: artifacts/data_ingestion]
[2024-02-25 22:24:40,772: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 22:24:44,422: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-02-25 22:24:44,532: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-02-25 22:24:44,538: INFO: main: *******************]
[2024-02-25 22:24:44,538: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-02-25 22:24:44,539: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:24:44,539: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:24:44,539: INFO: common: created directory at: artifacts]
[2024-02-25 22:24:44,539: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-02-25 22:24:44,733: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.
]
[2024-02-25 22:24:44,828: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.
]
[2024-02-25 22:24:45,201: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-02-25 22:24:45,424: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-02-25 22:24:45,425: INFO: main: *******************]
[2024-02-25 22:24:45,425: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-02-25 22:24:45,426: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:24:45,428: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:24:45,429: INFO: common: created directory at: artifacts]
[2024-02-25 22:24:45,429: INFO: common: created directory at: artifacts\training]
[2024-02-25 22:24:46,271: WARNING: module_wrapper: From C:\Users\Subhr\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.
]
[2024-02-25 22:25:01,380: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-25 22:25:01,386: INFO: main: *******************]
[2024-02-25 22:25:01,386: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-02-25 22:25:01,388: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-25 22:25:01,390: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-25 22:25:01,390: INFO: common: created directory at: artifacts]
[2024-02-25 22:25:03,521: INFO: common: json file saved at: scores.json]
[2024-02-25 22:25:03,521: INFO: common: json file saved at: scores.json]
[2024-02-25 22:25:06,758: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmp5ydkv0wl\model\data\model\assets]
[2024-02-25 22:25:19,046: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-02-26 03:06:12,758: INFO: utils: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.]
[2024-02-26 03:06:12,758: INFO: utils: NumExpr defaulting to 8 threads.]
[2024-02-26 03:06:13,695: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.127:8080]
[2024-02-26 03:06:13,695: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-02-26 03:06:22,003: INFO: _internal: 127.0.0.1 - - [26/Feb/2024 03:06:22] "GET / HTTP/1.1" 200 -]
[2024-04-27 07:18:44,942: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-27 07:18:44,950: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 07:18:44,950: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 07:18:44,950: INFO: common: created directory at: artifacts]
[2024-04-27 07:18:44,950: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 07:18:44,957: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 07:18:49,656: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 07:18:49,928: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-27 07:18:49,928: INFO: main: *******************]
[2024-04-27 07:18:49,928: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-27 07:18:49,935: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 07:18:49,940: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 07:18:49,940: INFO: common: created directory at: artifacts]
[2024-04-27 07:18:49,943: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-27 07:18:57,345: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-27 07:18:57,817: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-27 07:18:57,817: INFO: main: *******************]
[2024-04-27 07:18:57,824: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-27 07:18:57,824: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 07:18:57,831: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 07:18:57,831: INFO: common: created directory at: artifacts]
[2024-04-27 07:18:57,831: INFO: common: created directory at: artifacts\training]
[2024-04-27 07:19:20,478: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-27 07:19:20,478: INFO: main: *******************]
[2024-04-27 07:19:20,478: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-27 07:19:20,478: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 07:19:20,478: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 07:19:20,478: INFO: common: created directory at: artifacts]
[2024-04-27 07:19:23,182: INFO: common: json file saved at: scores.json]
[2024-04-27 07:19:23,198: INFO: common: json file saved at: scores.json]
[2024-04-27 07:19:27,745: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-27 07:19:28,983: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmpo3400out\model\data\model\assets]
[2024-04-27 07:20:47,296: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-27 07:25:17,248: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.167.230:8080]
[2024-04-27 07:25:17,248: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-27 07:25:33,345: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:25:33] "GET / HTTP/1.1" 200 -]
[2024-04-27 07:29:02,350: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.167.230:8080]
[2024-04-27 07:29:02,350: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-04-27 07:29:07,906: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:29:07] "GET / HTTP/1.1" 200 -]
[2024-04-27 07:32:03,636: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\Documents\github\mlops\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\Documents\github\mlops\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\losses.py", line 299, in from_config
    return cls(**config)
           ^^^^^^^^^^^^^
TypeError: CategoricalCrossentropy.__init__() got an unexpected keyword argument 'fn'
[2024-04-27 07:32:03,642: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:32:03] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-27 07:33:21,590: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:33:21] "GET / HTTP/1.1" 200 -]
[2024-04-27 07:33:24,152: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\Documents\github\mlops\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\Documents\github\mlops\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\losses.py", line 299, in from_config
    return cls(**config)
           ^^^^^^^^^^^^^
TypeError: CategoricalCrossentropy.__init__() got an unexpected keyword argument 'fn'
[2024-04-27 07:33:24,152: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:33:24] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-27 07:33:26,955: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:33:26] "GET / HTTP/1.1" 200 -]
[2024-04-27 07:37:13,724: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\Documents\github\mlops\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\Documents\github\mlops\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Subhr\anaconda3\envs\mlflow\Lib\site-packages\keras\losses.py", line 299, in from_config
    return cls(**config)
           ^^^^^^^^^^^^^
TypeError: CategoricalCrossentropy.__init__() got an unexpected keyword argument 'fn'
[2024-04-27 07:37:13,740: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:37:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-04-27 07:37:37,107: INFO: _internal: 127.0.0.1 - - [27/Apr/2024 07:37:37] "GET / HTTP/1.1" 200 -]
[2024-04-27 08:12:20,822: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-27 08:12:20,822: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:12:20,828: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:12:20,828: INFO: common: created directory at: artifacts]
[2024-04-27 08:12:20,828: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 08:12:20,831: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 08:12:25,745: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 08:12:26,002: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-27 08:12:26,002: INFO: main: *******************]
[2024-04-27 08:12:26,002: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-27 08:12:26,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:12:26,018: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:12:26,018: INFO: common: created directory at: artifacts]
[2024-04-27 08:12:26,018: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-27 08:12:26,833: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-27 08:12:27,272: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-27 08:12:27,272: INFO: main: *******************]
[2024-04-27 08:12:27,272: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-27 08:12:27,278: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:12:27,278: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:12:27,278: INFO: common: created directory at: artifacts]
[2024-04-27 08:12:27,284: INFO: common: created directory at: artifacts\training]
[2024-04-27 08:12:49,652: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-27 08:12:49,652: INFO: main: *******************]
[2024-04-27 08:12:49,652: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-27 08:12:49,652: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:12:49,652: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:12:49,652: INFO: common: created directory at: artifacts]
[2024-04-27 08:12:52,221: INFO: common: json file saved at: scores.json]
[2024-04-27 08:12:52,221: INFO: common: json file saved at: scores.json]
[2024-04-27 08:12:53,659: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-27 08:12:54,412: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmpbw01r04u\model\data\model\assets]
[2024-04-27 08:13:07,993: INFO: dir_util: creating C:\Users\Subhr\Documents\github\mlops\mlruns\0\889b1a6499344c1f88d55f83f26894c3\artifacts\model\data]
[2024-04-27 08:13:07,993: INFO: dir_util: creating C:\Users\Subhr\Documents\github\mlops\mlruns\0\889b1a6499344c1f88d55f83f26894c3\artifacts\model\data\model]
[2024-04-27 08:13:07,993: INFO: dir_util: creating C:\Users\Subhr\Documents\github\mlops\mlruns\0\889b1a6499344c1f88d55f83f26894c3\artifacts\model\data\model\assets]
[2024-04-27 08:13:08,005: INFO: dir_util: creating C:\Users\Subhr\Documents\github\mlops\mlruns\0\889b1a6499344c1f88d55f83f26894c3\artifacts\model\data\model\variables]
[2024-04-27 08:13:08,182: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-27 08:16:14,316: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-27 08:16:14,329: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:16:14,335: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:16:14,335: INFO: common: created directory at: artifacts]
[2024-04-27 08:16:14,335: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-27 08:16:14,335: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 08:16:18,859: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1NF_j8W2osQ3Ra0MwiQsAg-EVrN0KgydW/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 08:16:19,158: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-27 08:16:19,158: INFO: main: *******************]
[2024-04-27 08:16:19,158: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-27 08:16:19,165: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:16:19,169: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:16:19,169: INFO: common: created directory at: artifacts]
[2024-04-27 08:16:19,171: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-27 08:16:19,915: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-27 08:16:20,265: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-27 08:16:20,265: INFO: main: *******************]
[2024-04-27 08:16:20,265: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-27 08:16:20,265: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:16:20,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:16:20,281: INFO: common: created directory at: artifacts]
[2024-04-27 08:16:20,281: INFO: common: created directory at: artifacts\training]
[2024-04-27 08:16:42,499: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-27 08:16:42,500: INFO: main: *******************]
[2024-04-27 08:16:42,500: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-27 08:16:42,502: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-27 08:16:42,503: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-27 08:16:42,503: INFO: common: created directory at: artifacts]
[2024-04-27 08:16:45,073: INFO: common: json file saved at: scores.json]
[2024-04-27 08:16:45,074: INFO: common: json file saved at: scores.json]
[2024-04-27 08:16:49,510: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-27 08:16:50,672: INFO: builder_impl: Assets written to: C:\Users\Subhr\AppData\Local\Temp\tmp_rin1sib\model\data\model\assets]
[2024-04-27 08:18:08,875: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
